### PR TITLE
Visual character selection should have select caret

### PR DESCRIPTION
**Pull request by Kantis**
Fixes issue #1541 and replicates gVim behaviour

### CODE REVIEW

**Comment by Kantis** [comment]
Not sure if this should be achieved by setting IsSelectionInclusive somehow. I couldn't find any precedents and the global setting seems to always be Inclusive which gives us the block caret.

**Comment by jaredpar** [comment]
I don't believe this change is correct.  The Visual Character mode should use block selection.  Only when `selection=exclusive` should we be using the select caret which the current code does.

**Comment by Kantis** [comment]
Doh. I didn't know about the selection=inclusive / exclusive setting. Makes sense now, thanks.

**Comment by jaredpar** [comment]
@Kantis writing VsVim has caused me to learn about so many settings and commands I never knew existed :)

**Comment by Kantis** [comment]
Great way to learn :)

**Pull request closed without merging**
